### ISSUE TITLE
first console cmd after startup is not in history buffer

### ISSUE THREAD

**Issue by neogeographica** [andrei-drexler/ironwail#103] opened 2022-07-06 16:19 UTC
I'm currently running v0.6.0 built from source, on Linux (elementary/Ubuntu).

This is a minor thing but it bites me surprisingly often. For example I'll launch directly into some map using a shortcut, then immediately want to check something in the console... let's say I'm checking the value of r_softemu. So I enter that in the console. Then I want to actually set/change that value, so I press up arrow, but I get something other than r_softemu filled in at the prompt.

After a few experiments, it looks to me like whatever command I enter first, after Ironwail starts, is not saved in the console command history buffer (or if it's saved, it's not properly recalled). Everything after that first command is saved and recalled as expected.

**Comment by andrei-drexler** [comment] 2022-07-08 08:07
I can't reproduce this on either Windows or Ubuntu (tried both gcc and clang). Does it happen 100% of the time for you?

**Comment by neogeographica** [comment] 2022-07-08 16:35
Yep!

Simple repro case for me:

* Launch Ironwail with no arguments.
* Open the console.
* Enter "deathmatch" in the console, press Enter, see the current value (0) displayed.
* Press up arrow. I would expect to get "deathmatch" filled in. Instead I get something else like "noclip".

**Comment by andrei-drexler** [comment] 2022-07-12 21:59
Hmm, you're right, that's not it. My next guess: you also use QSS/QSS-M with the same Quake dir sometimes :) Fixed in ec5a141a4bab58e1be32207c3e668b7c927bc31c.

**Closed by andrei-drexler** 2022-07-12 21:59 UTC

**Comment by neogeographica** [comment] 2022-07-12 22:03
Hmm! Well, I haven't in quite a long time, but I did used to run QSS out of this Quake dir.

As an experiment I tried deleting the current history.txt file and the bug seems to go away... not sure if that confirms your theory?

**Comment by andrei-drexler** [comment] 2022-07-12 22:29
Kind of. I was only able to reproduce this by editing history.txt to have more than 32 lines, with the last one being the prompt that I'd enter first thing after starting up. Before the fix, the file was getting trimmed to <32 lines if a new command was entered in the console. QSS [fixed](https://github.com/Shpoike/Quakespasm/commit/e63dae5f49b8773c52e91720bc1597400ab095e5) this bug a couple of years ago, so it's much more likely to write files with >32 lines.

Anyway, feel free to reopen this if you spot it again.
